### ISSUE TITLE
[11.0] Buffer adjustments issue

### ISSUE THREAD

**Issue by didierdonze** [OCA/ddmrp#8]
We face the issue that the buffers are not updated after confirming a PO for instance. @guewen investigated on it and found a possible candidate for it:
https://github.com/OCA/stock-logistics-warehouse/pull/375/files#diff-65190c8c38ef3b3e1094f032c1298735R68

- There is no quant with `('contains_unreserved', '=', True)`
- We should investigate and find why the quants are not updated

**Comment by LoisRForgeFlow** [comment]
What do you refer to? the buffer zones aren't being updated because the `qty_available_not_res` is not being updated? or the zones aren't being updated but the `qty_available_not_res` is?

**Comment by guewen** [comment]
`qty_available_not_res` is always zero. Because at this point: https://github.com/OCA/stock-logistics-warehouse/blob/61b1723409fb89e8056fa623b01eacaec21c072c/stock_available_unreserved/models/product.py#L64-L72 the domain exclude quants that don't have `('contains_unreserved', '=', True)`, but the quants seem to always have a False `contains_unreserved`.

**Comment by guewen** [comment]
Fixed at https://github.com/OCA/stock-logistics-warehouse/pull/401
